version: '3'
services:
  backend:
    build:
      context: ./backend
    env_file:
      - ../.env
    volumes:
      - shared_data:/app/shared
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    volumes:
      - shared_data:/app/shared
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  shared_data:
